---
name: OpenCode
on:
  issue_comment:
    types:
      - created
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited
  issues:
    types:
      - opened
  pull_request_review:
    types:
      - submitted
  workflow_call:
  workflow_dispatch:
jobs:
  opencode:
    uses: Cogni-AI-OU/.github/.github/workflows/opencode.yml@main
    permissions:
      actions: read
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit  # pragma: allowlist secret
